#include "website.h"
#include <sstream>

String generate_website(float *temp_data, float *humidity_data, size_t samples) {
    std::ostringstream oss;
    oss << "<!DOCTYPE html>\n"
           "<html lang=\"en\">\n"
           "  <head>\n"
           "    <meta charset=\"UTF-8\" />\n"
           "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
           "    <title>Temperature Server</title>\n"
           "\n"
           "    <script src=\"https://cdn.tailwindcss.com\"></script>\n"
           "    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n"
           "\n"
           "    <style>\n"
           "      :root {\n"
           "        --bg: #0b0f14;\n"
           "        --panel: #121826;\n"
           "        --panel-soft: #0f1420;\n"
           "        --border: rgba(255,255,255,0.06);\n"
           "        --muted: #94a3b8;\n"
           "        --text: #e5e7eb;\n"
           "      }\n"
           "\n"
           "      .panel {\n"
           "        background: var(--panel);\n"
           "        border: 1px solid var(--border);\n"
           "        border-radius: 1rem;\n"
           "        padding: 1.25rem;\n"
           "      }\n"
           "\n"
           "      .label {\n"
           "        font-size: 0.7rem;\n"
           "        letter-spacing: 0.12em;\n"
           "        text-transform: uppercase;\n"
           "        color: var(--muted);\n"
           "      }\n"
           "\n"
           "      .stat-value {\n"
           "        margin-top: 0.25rem;\n"
           "        font-size: 1.9rem;\n"
           "        font-weight: 600;\n"
           "        color: #fff;\n"
           "      }\n"
           "\n"
           "      .timespan {\n"
           "        display: inline-flex;\n"
           "        gap: 0.25rem;\n"
           "        background: var(--panel-soft);\n"
           "        border: 1px solid var(--border);\n"
           "        border-radius: 0.75rem;\n"
           "        padding: 0.25rem;\n"
           "      }\n"
           "\n"
           "      .timespan button {\n"
           "        appearance: none;\n"
           "        background: transparent;\n"
           "        border: none;\n"
           "        padding: 0.35rem 0.65rem;\n"
           "        border-radius: 0.5rem;\n"
           "        font-size: 0.85rem;\n"
           "        letter-spacing: 0.05em;\n"
           "        text-transform: uppercase;\n"
           "        color: var(--muted);\n"
           "        cursor: pointer;\n"
           "      }\n"
           "\n"
           "      .timespan button:hover {\n"
           "        background: rgba(255,255,255,0.06);\n"
           "        color: var(--text);\n"
           "      }\n"
           "\n"
           "      .timespan button.active {\n"
           "        background: var(--panel);\n"
           "        color: #fff;\n"
           "      }\n"
           "    </style>\n"
           "  </head>\n"
           "  <body class=\"min-h-screen bg-[var(--bg)] text-[var(--text)] flex items-center justify-center\">\n"
           "    <main class=\"w-full max-w-6xl px-6 py-10 flex flex-col items-center gap-4\">\n"
           "      <!-- Stats -->\n"
           "      <section class=\"panel flex gap-12\">\n"
           "        <div>\n"
           "          <div class=\"label\">Temperature</div>\n"
           "          <div class=\"stat-value\" id=\"tempStat\">22.4<span class=\"text-base text-slate-400\">°C</span></div>\n"
           "        </div>\n"
           "        <div>\n"
           "          <div class=\"label\">Humidity</div>\n"
           "          <div class=\"stat-value\" id=\"humidityStat\">48<span class=\"text-base text-slate-400\">%</span></div>\n"
           "        </div>\n"
           "      </section>\n"
           "\n"
           "      <!-- Timespan -->\n"
           "      <section class=\"flex justify-center\">\n"
           "        <div class=\"timespan\" id=\"timespan\">\n"
           "          <button data-span=\"24h\">24h</button>\n"
           "          <button data-span=\"12h\">12h</button>\n"
           "          <button data-span=\"6h\" class=\"active\">6h</button>\n"
           "          <button data-span=\"1h\">1h</button>\n"
           "          <button data-span=\"15m\">15m</button>\n"
           "        </div>\n"
           "      </section>\n"
           "\n"
           "      <!-- Charts -->\n"
           "      <section class=\"w-full flex flex-col gap-2\">\n"
           "        <div class=\"panel\">\n"
           "          <div class=\"label mb-3\">Temperature</div>\n"
           "          <div class=\"h-64\"><canvas id=\"tempChart\"></canvas></div>\n"
           "        </div>\n"
           "        <div class=\"panel\">\n"
           "          <div class=\"label mb-3\">Humidity</div>\n"
           "          <div class=\"h-64\"><canvas id=\"humidityChart\"></canvas></div>\n"
           "        </div>\n"
           "      </section>\n"
           "    </main>\n"
           "\n"
           "    <script>\n"
           "      const TIMESPANS = {\n"
           "        '24h': { minutes: 24*60, step: 60 },\n"
           "        '12h': { minutes: 12*60, step: 60 },\n"
           "        '6h':  { minutes: 6*60,  step: 30 },\n"
           "        '1h':  { minutes: 1*60,  step: 5  },\n"
           "        '15m': { minutes: 15,    step: 1  }\n"
           "      };\n"
           "      const DEFAULT_TIMESPAN = '6h';\n"
           "      // DATA is sampled every minute\n"
           "      const DATA = {\n"
           "        temp: [";
    for (size_t i = 0; i < samples; i++) {
        oss << temp_data[i];
        if (i < samples-1) oss << ",";
    }
    oss << "],\n"
           "        humidity: [";
    for (size_t i = 0; i < samples; i++) {
        oss << humidity_data[i];
        if (i < samples-1) oss << ",";
    }
    oss << "]\n"
           "      }\n"
           "\n"
           "      const chartOptions = {\n"
           "        responsive: true,\n"
           "        maintainAspectRatio: false,\n"
           "        plugins: { legend: { display: false } },\n"
           "        scales: {\n"
           "          x: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: '#94a3b8' } },\n"
           "          y: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: '#94a3b8' } }\n"
           "        }\n"
           "      };\n"
           "\n"
           "      function createChart(id) {\n"
           "        return new Chart(document.getElementById(id), {\n"
           "          type: 'line',\n"
           "          data: { labels: [], datasets: [{ data: [], borderWidth: 2, tension: 0.35 }] },\n"
           "          options: chartOptions\n"
           "        });\n"
           "      }\n"
           "\n"
           "      const tempChart = createChart('tempChart');\n"
           "      const humidityChart = createChart('humidityChart');\n"
           "\n"
           "      function setData(span) {\n"
           "        const { minutes, step } = TIMESPANS[span];\n"
           "        const len = DATA.temp.length;\n"
           "\n"
           "        let labels = [];\n"
           "        let tempData = [];\n"
           "        let humidityData = [];\n"
           "\n"
           "        for (let i = len-1; i >= Math.max(0, len-1-minutes); i -= step) {\n"
           "          const minutesAgo = len-1-i;\n"
           "          labels.push(minutesAgo >= 60 ? `-${Math.round(minutesAgo/60*10)/10}h` : `-${minutesAgo}m`);\n"
           "          tempData.push(DATA.temp[i]);\n"
           "          humidityData.push(DATA.humidity[i]);\n"
           "        }\n"
           "\n"
           "        labels = labels.reverse();\n"
           "        tempData = tempData.reverse();\n"
           "        humidityData = humidityData.reverse();\n"
           "\n"
           "        tempChart.data.labels = labels;\n"
           "        tempChart.data.datasets[0].data = tempData;\n"
           "        tempChart.update();\n"
           "\n"
           "        humidityChart.data.labels = labels;\n"
           "        humidityChart.data.datasets[0].data = humidityData;\n"
           "        humidityChart.update();\n"
           "\n"
           "        return [tempData, humidityData];\n"
           "      }\n"
           "\n"
           "      function setTimespan(span) {\n"
           "        document.querySelectorAll('#timespan button').forEach(b => {\n"
           "          b.classList.toggle('active', b.dataset.span === span);\n"
           "        });\n"
           "\n"
           "        const [tempData, humidityData] = setData(span);\n"
           "\n"
           "        document.getElementById('tempStat').innerHTML = `${tempData.at(-1)}<span class=\"text-base text-slate-400\">°C</span>`;\n"
           "        document.getElementById('humidityStat').innerHTML = `${humidityData.at(-1)}<span class=\"text-base text-slate-400\">%</span>`;\n"
           "      }\n"
           "\n"
           "      document.querySelectorAll('#timespan button').forEach(btn => {\n"
           "        btn.addEventListener('click', () => setTimespan(btn.dataset.span));\n"
           "      });\n"
           "\n"
           "      setTimespan(DEFAULT_TIMESPAN);\n"
           "    </script>\n"
           "  </body>\n"
           "</html>\n";
    return String(oss.str().c_str());
}
